# Generated by Django 5.2.1 on 2025-07-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_alter_user_school_year_alter_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
