# Generated by Django 5.2.1 on 2025-07-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_user_is_manager_delete_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='school_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='university',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
