# Generated by Django 5.2.1 on 2025-07-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_alter_lecture_average_score_alter_lecture_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
